name: CI

on:
  workflow_dispatch:
  push:
    branches: main
    paths-ignore:
    - "scripts/**"
    - "misc/**"
    - "*.md"
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review
    paths-ignore:
      - "scripts/**"
      - "misc/**"
      - "*.md"

permissions:
  pull-requests: read
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  DOTNET_NUGET_SIGNATURE_VERIFICATION: false
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache dotnet
        uses: actions/cache@v4
        with:
          lookup-only: ${{ github.event_name != 'push'}}
          path: ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/csproj','**/Directory.Build.props') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: build
        run: dotnet build --configuration Release

      - name: test
        run: dotnet test --logger:"junit" --collect:"XPlat Code Coverage"

      - name: Upload cov results to Codecov
        if: ${{!cancelled()}}
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{!cancelled()}}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "**/TestResults.xml"
          fail_ci_if_error: true
